<a href="https://colab.research.google.com/github/nirmaljb/deep-learning-notebooks/blob/main/ovarian_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
cancer = pd.read_csv('/content/drive/MyDrive/ovariantotal.csv')
cancer.head()

AFP     AG  Age   ALB  ALP  ALT  ...   RBC   RDW  TBIL    TP     UA  TYPE
0   3.58  19.36   47  45.4   56   11  ...  2.64  13.7   5.5  73.9  396.4     0
1  34.24  23.98   61  39.9   95    9  ...  4.89  12.7   6.8  72.0  119.2     0
2   1.50  18.40   39  45.4   77    9  ...  4.62  12.0  14.8  77.9  209.2     0
3   2.75  16.60   45  39.2   26   16  ...  4.01  14.6  10.9  66.1  215.6     0
4   2.36  19.97   45  35.0   47   21  ...  4.40  13.4   5.3  66.5  206.0     0

[5 rows x 50 columns]

In [3]:
cancer.shape

(349, 50)

In [4]:
X = cancer.drop('TYPE', axis=1)
y = cancer['TYPE']

In [5]:
y

0      0
1      0
2      0
3      0
4      0
      ..
344    1
345    1
346    1
347    1
348    1
Name: TYPE, Length: 349, dtype: int64

In [6]:
from sklearn import preprocessing
min_max_scalar = preprocessing.MinMaxScaler()
X_scale = min_max_scalar.fit_transform(X)
print(X_scale)

[[2.45578349e-03 4.85071876e-01 4.70588235e-01 ... 8.37988827e-02
  7.60667904e-01 5.60447761e-01]
 [2.78074070e-02 6.55363067e-01 6.76470588e-01 ... 1.20111732e-01
  7.25417440e-01 4.32835821e-02]
 [7.35908185e-04 4.49686694e-01 3.52941176e-01 ... 3.43575419e-01
  8.34879406e-01 2.11194030e-01]
 ...
 [1.83563615e-03 4.80280133e-01 6.47058824e-01 ... 3.15642458e-01
  6.58627087e-01 2.11753731e-01]
 [1.01704165e-03 7.74788058e-01 2.20588235e-01 ... 2.45810056e-01
  7.99628942e-01 3.53917910e-01]
 [8.26863129e-04 2.50645042e-01 3.52941176e-01 ... 1.62011173e-01
  6.62337662e-01 1.65858209e-01]]


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scale, y, test_size=0.2, random_state=0)

In [8]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(32, activation='relu', input_dim=49))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=32, epochs=5)

Epoch 1/5
9/9 ━━━━━━━━━━━━━━━━━━━━ 3s 92ms/step - accuracy: 0.4935 - loss: 0.7018
Epoch 2/5
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7535 - loss: 0.6586 
Epoch 3/5
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7700 - loss: 0.6369 
Epoch 4/5
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8018 - loss: 0.6052 
Epoch 5/5
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7909 - loss: 0.5860 


In [10]:
y_pred = model.predict(X_test)
y_pred

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step


array([[0.59752107],
       [0.4489999 ],
       [0.5814329 ],
       [0.3197496 ],
       [0.62882906],
       [0.6428241 ],
       [0.65969306],
       [0.4356927 ],
       [0.3346298 ],
       [0.641931  ],
       [0.6200284 ],
       [0.42994237],
       [0.68614185],
       [0.44336852],
       [0.30267277],
       [0.5628011 ],
       [0.5618457 ],
       [0.6406437 ],
       [0.6646185 ],
       [0.47346988],
       [0.58394045],
       [0.5972068 ],
       [0.39260972],
       [0.6329581 ],
       [0.31900078],
       [0.61946887],
       [0.28309372],
       [0.37149683],
       [0.3222892 ],
       [0.68222404],
       [0.529887  ],
       [0.48394266],
       [0.33354074],
       [0.36509576],
       [0.40904525],
       [0.23783025],
       [0.54364073],
       [0.6010547 ],
       [0.38362077],
       [0.43950802],
       [0.6024899 ],
       [0.59972125],
       [0.620496  ],
       [0.6427643 ],
       [0.65126306],
       [0.27779245],
       [0.44133803],
       [0.608

In [11]:
y_pred = np.where(y_pred > 0.5, 1, 0)
y_pred = y_pred.astype(int)
import numpy as np

np.column_stack((y_pred, y_test))

array([[1, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0,

In [12]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[30 11]
 [ 3 26]]
0.8


In [13]:
from tensorflow.keras.layers import Dropout
model = Sequential()

model.add(Dense(32, activation='relu', input_dim=49))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))

#output
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [14]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, validation_split=0.2, batch_size=32, epochs=10)

Epoch 1/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 6s 376ms/step - accuracy: 0.5977 - loss: 0.6573 - val_accuracy: 0.7143 - val_loss: 0.6521
Epoch 2/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6372 - loss: 0.6602 - val_accuracy: 0.6786 - val_loss: 0.6372
Epoch 3/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5943 - loss: 0.6642 - val_accuracy: 0.6964 - val_loss: 0.6279
Epoch 4/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7060 - loss: 0.6034 - val_accuracy: 0.7321 - val_loss: 0.6171
Epoch 5/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6782 - loss: 0.6128 - val_accuracy: 0.7679 - val_loss: 0.6070
Epoch 6/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7094 - loss: 0.6111 - val_accuracy: 0.7679 - val_loss: 0.5912
Epoch 7/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7091 - loss: 0.5974 - val_accuracy: 0.7857 - val_loss: 0.5800
Epoch 8/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6951 - loss: 0.5782 - val_accuracy: 0.7679 - val_loss: 0.5699

In [15]:
y_pred = model.predict(X_test)
y_pred
y_pred = np.where(y_pred > 0.5, 1, 0)
y_pred = y_pred.astype(int)
import numpy as np

np.column_stack((y_pred, y_test))

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step


array([[1, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0,

In [16]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[31 10]
 [ 3 26]]
0.8142857142857143


In [17]:
from keras.callbacks import EarlyStopping
model = Sequential()

model.add(Dense(32, activation='relu', input_dim=49))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))

#output
model.add(Dense(1, activation='sigmoid'))
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [18]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, validation_split=0.2, batch_size=8, epochs=100, callbacks=[early_stop], verbose=1)

Epoch 1/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 5s 71ms/step - accuracy: 0.5480 - loss: 0.6845 - val_accuracy: 0.7321 - val_loss: 0.6514
Epoch 2/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6678 - loss: 0.6381 - val_accuracy: 0.7679 - val_loss: 0.6333
Epoch 3/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6288 - loss: 0.6288 - val_accuracy: 0.7143 - val_loss: 0.5974
Epoch 4/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7215 - loss: 0.5982 - val_accuracy: 0.7857 - val_loss: 0.5736
Epoch 5/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7615 - loss: 0.5582 - val_accuracy: 0.7679 - val_loss: 0.5370
Epoch 6/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7267 - loss: 0.5555 - val_accuracy: 0.8036 - val_loss: 0.5305
Epoch 7/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7419 - loss: 0.5417 - val_accuracy: 0.7321 - val_loss: 0.5012
Epoch 8/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7379 - loss: 0.5140 - val_accuracy: 0.8036 - 

In [19]:
y_pred = model.predict(X_test)
y_pred
y_pred = np.where(y_pred > 0.5, 1, 0)
y_pred = y_pred.astype(int)
import numpy as np

np.column_stack((y_pred, y_test))

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

1/3 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step
[[30 11]
 [ 3 26]]
0.8


In [22]:
from tensorflow.keras import layers, models, regularizers
model = Sequential()

model.add(Dense(32, activation='relu', kernel_regularizer=regularizers.L1(0.001), input_dim=49))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu', kernel_regularizer=regularizers.L1(0.001)))
model.add(Dropout(0.2))

#output
model.add(Dense(1, activation='sigmoid'))
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [23]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, validation_split=0.2, batch_size=8, epochs=100, callbacks=[early_stop], verbose=1)

Epoch 1/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 6s 115ms/step - accuracy: 0.4687 - loss: 1.0681 - val_accuracy: 0.5893 - val_loss: 1.0187
Epoch 2/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5700 - loss: 1.0075 - val_accuracy: 0.8036 - val_loss: 0.9739
Epoch 3/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5929 - loss: 0.9851 - val_accuracy: 0.7500 - val_loss: 0.9267
Epoch 4/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6662 - loss: 0.9281 - val_accuracy: 0.7679 - val_loss: 0.8870
Epoch 5/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6951 - loss: 0.8779 - val_accuracy: 0.7321 - val_loss: 0.8581
Epoch 6/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7312 - loss: 0.8486 - val_accuracy: 0.7500 - val_loss: 0.8129
Epoch 7/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8125 - loss: 0.7833 - val_accuracy: 0.7500 - val_loss: 0.7850
Epoch 8/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7024 - loss: 0.7944 - val_accuracy: 0.7679 

In [24]:
y_pred = model.predict(X_test)
y_pred
y_pred = np.where(y_pred > 0.5, 1, 0)
y_pred = y_pred.astype(int)
import numpy as np

np.column_stack((y_pred, y_test))

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 173ms/step
[[30 11]
 [ 1 28]]
0.8285714285714286


In [ ]:
import keras
print(keras.__version__)

import tensorflow as tf
print(tf.__version__)